import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import html2canvas from 'html2canvas';
import * as XLSX from 'xlsx';
import jbmLogoUrl from '../assets/jbmlogo (1).png';
import roseLogoUrl from '../assets/rose logo (1).png';

// Placeholder legal/plant name shown in exported report headers - update to the exact entity
// name if it differs (e.g. "Rose Engineered Products India Pvt. Ltd.").
export const PLANT_NAME = 'Rose Engineered Products India Pvt. Ltd.';

export function formatDuration(totalSeconds) {
  const seconds = Math.round(totalSeconds || 0);
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  if (hours > 0) return `${hours}h ${minutes}m`;
  return `${minutes}m ${seconds % 60}s`;
}

/**
 * "X hr Y min" / "Y min" - the wording used specifically in PDF/Excel exports (report readers
 * expect plain hours-and-minutes, not raw seconds or the abbreviated h/m used on-screen).
 */
export function formatDurationHm(totalSeconds) {
  const totalMinutes = Math.round((totalSeconds || 0) / 60);
  const hours = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;
  if (hours > 0) return `${hours} hr ${minutes} min`;
  return `${minutes} min`;
}

function formatTimeOnly(value) {
  if (!value) return '?';
  return new Date(value).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', hour12: false });
}

/** "13:00 – 13:05" (or "13:00 – Active" for a still-open downtime event). */
export function formatTimeRange(startTime, endTime) {
  return `${formatTimeOnly(startTime)} – ${endTime ? formatTimeOnly(endTime) : 'Active'}`;
}

// The source logo files are multi-megabyte PNGs (full marketing-asset resolution). jsPDF embeds
// whatever pixel data it's given verbatim, regardless of the small mm size it's displayed at -
// passing the raw file straight through made every page of every export carry ~5MB of logo data
// it didn't need. Downscaling once, here, to a size that's still sharp at print resolution
// (~500px wide, comfortably above what 36mm/28mm needs at 300dpi) keeps exports a normal size.
function loadImage(src, maxWidth = 500) {
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => {
      const scale = Math.min(1, maxWidth / img.width);
      const width = Math.round(img.width * scale);
      const height = Math.round(img.height * scale);
      const canvas = document.createElement('canvas');
      canvas.width = width;
      canvas.height = height;
      canvas.getContext('2d').drawImage(img, 0, 0, width, height);
      resolve({ dataUrl: canvas.toDataURL('image/png'), width, height });
    };
    img.onerror = () => resolve(null);
    img.src = src;
  });
}

// Logos never change at runtime - fetch once and reuse across every export call this session.
let logoPromise = null;
function getLogos() {
  if (!logoPromise) logoPromise = Promise.all([loadImage(jbmLogoUrl), loadImage(roseLogoUrl)]);
  return logoPromise;
}

/**
 * Draws the report header (JBM logo top-left, rose logo top-right, plant name, report title,
 * machine name, applied filters, generation date/time, Generated By) on the CURRENT page of an
 * open jsPDF document. Called once per page so a multi-page export keeps the same header
 * everywhere, not just page 1.
 */
async function drawHeader(doc, { title, machineName, filtersText, generatedBy }) {
  const [jbm, rose] = await getLogos();
  const pageWidth = doc.internal.pageSize.getWidth();
  const logoTop = 8;

  // Logos sized well above the text block (36mm/28mm) so they read clearly on a printed page -
  // header height below is computed from whichever is tallest, so this stays correct regardless
  // of either logo's actual aspect ratio.
  let logoBottom = logoTop;
  if (jbm) {
    const w = 36;
    const h = (jbm.height / jbm.width) * w;
    doc.addImage(jbm.dataUrl, 'PNG', 12, logoTop, w, h);
    logoBottom = Math.max(logoBottom, logoTop + h);
  }
  if (rose) {
    const w = 28;
    const h = (rose.height / rose.width) * w;
    doc.addImage(rose.dataUrl, 'PNG', pageWidth - 12 - w, logoTop, w, h);
    logoBottom = Math.max(logoBottom, logoTop + h);
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(20, 20, 20);
  doc.text(PLANT_NAME, pageWidth / 2, 14, { align: 'center' });
  doc.setFontSize(10);
  doc.text(title, pageWidth / 2, 20, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text(`Machine: ${machineName}`, pageWidth / 2, 25, { align: 'center' });
  doc.text(filtersText, pageWidth / 2, 29.5, { align: 'center' });
  doc.text(`Generated: ${new Date().toLocaleString()}  |  Generated By: ${generatedBy || 'Unknown'}`, pageWidth / 2, 34, { align: 'center' });

  const dividerY = Math.max(38, logoBottom + 4);
  doc.setDrawColor(225, 225, 225);
  doc.line(12, dividerY, pageWidth - 12, dividerY);

  return dividerY + 6; // y-cursor where page content can start
}

/** Stamps the footer + "Page X of Y" on every page, once the document's full page count is known. */
function finalizePdf(doc) {
  const pageCount = doc.internal.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7.5);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by CNC Monitoring System', 12, pageHeight - 7);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 12, pageHeight - 7, { align: 'right' });
  }
}

async function captureElement(el) {
  if (!el) return null;
  try {
    // scale: 3 renders at ~3x device pixel density so chart labels/legends stay sharp even
    // after being blown up to near-full-page size in the PDF (a low-res capture stretched to
    // that size is what made the earlier export's chart text unreadable). JPEG (not PNG) for
    // this one - it's a flat-color/text screenshot, not a photo, so quality loss is negligible
    // but the file comes out a fraction of the size of an equivalent PNG at this resolution.
    const canvas = await html2canvas(el, { scale: 3, backgroundColor: '#ffffff', useCORS: true });
    return { dataUrl: canvas.toDataURL('image/jpeg', 0.92), format: 'JPEG' };
  } catch {
    return null; // export must still succeed without the chart snapshot
  }
}

function addImageFitted(doc, image, y, marginX = 10) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const imgProps = doc.getImageProperties(image.dataUrl);
  let width = pageWidth - marginX * 2;
  let height = (imgProps.height / imgProps.width) * width;
  const maxHeight = pageHeight - y - 12;
  if (height > maxHeight) {
    height = maxHeight;
    width = (imgProps.width / imgProps.height) * height;
  }
  doc.addImage(image.dataUrl, image.format, marginX, y, width, height);
  return y + height + 6;
}

/**
 * Generic report PDF: repeated header/footer, an optional KPI grid, an optional chart-area
 * screenshot, and one or more titled detail tables. Used by the OEE report, the Downtime
 * Analysis tab, and the Downtime Events drawer - one export implementation, several callers.
 */
export async function exportPdf({ title, machineName, filtersText, generatedBy, kpiRows, chartsEl, tables = [], fileName, orientation = 'landscape' }) {
  const doc = new jsPDF({ orientation, unit: 'mm', format: 'a4' });
  let y = await drawHeader(doc, { title, machineName, filtersText, generatedBy });

  if (kpiRows && kpiRows.length > 0) {
    autoTable(doc, {
      startY: y,
      head: [['KPI', 'Value', 'KPI', 'Value']],
      body: kpiRows,
      theme: 'grid',
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [0, 87, 255] },
      margin: { left: 12, right: 12 }
    });
    y = doc.lastAutoTable.finalY + 6;
  }

  if (chartsEl) {
    const imgData = await captureElement(chartsEl);
    if (imgData) {
      // Charts get a dedicated page (rather than whatever space is left after the KPI table)
      // so they render at close to full-page size - fitting them into leftover space is what
      // previously made the chart text/legends too small to read.
      doc.addPage();
      y = await drawHeader(doc, { title, machineName, filtersText, generatedBy });
      y = addImageFitted(doc, imgData, y);
    }
  }

  for (const table of tables) {
    if (y > doc.internal.pageSize.getHeight() - 40) {
      doc.addPage();
      y = await drawHeader(doc, { title, machineName, filtersText, generatedBy });
    }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(30, 30, 30);
    doc.text(table.title, 12, y);
    autoTable(doc, {
      startY: y + 3,
      head: [table.head],
      body: table.body,
      theme: 'striped',
      styles: { fontSize: 7.5, cellPadding: 2 },
      headStyles: { fillColor: [30, 41, 59] },
      margin: { left: 12, right: 12 }
    });
    y = doc.lastAutoTable.finalY + 8;
  }

  finalizePdf(doc);
  doc.save(fileName);
}

/** One workbook, multiple named sheets - each `sheets[i].rows` is an array of plain objects. */
export function exportExcel({ sheets, fileName }) {
  const wb = XLSX.utils.book_new();
  sheets.forEach(({ name, rows }) => {
    const ws = XLSX.utils.json_to_sheet(rows && rows.length > 0 ? rows : [{}]);
    XLSX.utils.book_append_sheet(wb, ws, name.slice(0, 31));
  });
  XLSX.writeFile(wb, fileName);
}

/** Print via the browser - @media print rules (index.css) isolate the `.print-area` element. */
export function printReport() {
  window.print();
}

/**
 * Prints a single DOM element in isolation (used by modals/drawers, e.g. the Downtime Events
 * drawer's "Print Downtime Report" button) - opens a new window, carries over the app's
 * stylesheets so Tailwind classes still render, and prints only that element's markup. Avoids
 * fighting the page-level `.print-area` isolation (index.css), which is scoped to the full
 * report page, not a modal stacked on top of it.
 */
export function printElement(el, title = 'Report') {
  if (!el) return;
  const printWindow = window.open('', '_blank', 'width=1200,height=800');
  if (!printWindow) return;

  const styles = Array.from(document.querySelectorAll('style, link[rel="stylesheet"]'))
    .map((node) => node.outerHTML)
    .join('\n');

  printWindow.document.write(`<!doctype html><html><head><title>${title}</title>${styles}</head><body>${el.outerHTML}</body></html>`);
  printWindow.document.close();
  printWindow.onload = () => {
    printWindow.focus();
    printWindow.print();
    printWindow.close();
  };
}
